# Setup
title: Jim Shadrick
url: https://jimshadrick.github.io/
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: jimshadrick
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/jimshadrick 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: jcshadrick
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"


sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Jim Shadrick
  url: https://twitter.com/jcshadrick
  email: jshadrick@live.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
